[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
build_info = true
extra_output = ["storageLayout"]
[rpc_endpoints]
sepolia = "QUICKNODE_ENDPOINT_URL"
[fuzz]
runs = 256
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
